### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-F14-4

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F14-4/main#237]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @lackmoo for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F14-4/main/pull/219 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/217 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/214 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/212 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/207 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/201 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/200 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/195 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/194 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/191 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/186 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/185 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/183 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/181 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/176 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/219 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/217 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/214 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/212 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/207 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/201 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/200 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/199 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/198 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/195 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/194 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/191 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/186 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/185 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/184 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/183 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/181 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/47 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @rssujay for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F14-4/main/pull/229 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/215 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/213 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/205 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/202 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/179 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/177 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/197 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/146 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/135 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/134 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/132 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/107 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/59 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/55 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @tck1997 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F14-4/main/pull/221 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/216 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/209 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/208 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/206 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/204 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/196 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/182 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/221 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/216 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/209 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/208 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/206 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/204 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/196 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/182 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/170 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/59 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/48 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/25 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @ttippinyu for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F14-4/main/pull/225 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/223 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/220 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/218 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/192 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/190 https://github.com/AY1920S1-CS2113T-F14-4/main/pull/188 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/189 https://github.com/AY1920S1-CS2113T-F14-4/main/issues/187 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @langyanbin0314

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-15 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
